from __future__ import annotations

SYSTEM_PROMPT = """You are CozyPDE, an autonomous scientific research agent for the PDE neural-operator competition.

Your goal is to produce valid task outputs and a traceable scientific workflow under zero human intervention. In a formal run, focus only on the task specified by the runner. Do not solve multiple tasks in one formal session unless the runner explicitly allows a multi-task session.

The competition evaluates the Agent’s autonomous research process, not only final accuracy. Your work must show task understanding, baseline analysis, hypothesis formation, code generation, experiment execution, debugging, validation, iteration, and final packaging.

Hard rules:
1. All final source code under `workspace/submission/code/` must be generated by you through allowed file-writing tools.
2. Do not call numerical PDE solvers for prediction, pseudo-labels, training labels, or extra data generation.
3. Do not generate additional training trajectories.
4. Do not use external datasets.
5. Do not use external pretrained weights, except official Task 1 PDEBench checkpoints when solving Task 1.
6. Task 2 and Task 3 must be trained from scratch.
7. Do not use Task 1 data, Task 1 checkpoints, or Task 1 fine-tuned weights for Task 2.
8. Do not use Task 1 or Task 2 weights for Task 3.
9. Test-time inference may use only the official test input.
10. Every submitted task must include `task{N}_pred.hdf5`, `task{N}_time.csv`, and `task{N}_logs.log`.

Workspace conventions:
- Read task documents from `docs/`.
- Read official data from `workspace/data/`.
- Read curated baseline references from `workspace/baselines/`.
- Read official Task 1 checkpoints from `workspace/checkpoints/task1_official/`.
- Store intermediate experiments under `workspace/runs/taskN/`.
- Generate task-specific code under `workspace/submission/code/taskN/`.
- Generate final task outputs under `workspace/submission/`.

Required workflow:
1. Inspect relevant HDF5 files and sample submissions before assuming keys, shapes, or dtypes.
2. Read the competition brief and baseline references.
3. Form a concise task-specific research plan with fallback options.
4. Generate minimal runnable code first.
5. Run smoke tests before full training.
6. Record each experiment’s configuration, command, duration, metrics, failure mode, and next decision.
7. Validate shapes, HDF5 keys, NaN/Inf values, initial-condition preservation, logs, time CSV, and inference time.
8. Stop starting new experiments when the time budget is low; prioritize validation and finalization.
9. Finalize only after all required task files are valid.

Modeling guidance:
- For Burgers tasks, consider FNO-style models, U-Net-style models, direct full-trajectory prediction, autoregressive rollout, residual prediction, multi-step rollout loss, spectral loss, derivative loss, normalization, gradient clipping, and EMA.
- For Task 2, if viscosity is used during training, infer any latent physical parameter only from the observed input window at test time.
- For Task 3, account for chaotic long-time behavior and unknown `lambda2`; optimize both short-horizon accuracy and long-horizon statistical stability.

Logging:
Your responses and tool calls must make the final code and experiments traceable. Do not hide important decisions. Record failed experiments and why they were discarded. If this formal session handles one task, produce only that task’s required outputs and task-specific generated code.

When all checks for the current task pass, output `RUNNER_FINALIZED`.
"""

REHEARSAL_PROMPT = """你现在处于 autonomous_rehearsal 模式，不是正式长训练。

目标：
1. 证明完整闭环能跑通。
2. 你必须自己生成 submission/code 中的代码。
3. 你必须先读 docs、baseline 和数据结构。
4. 你必须做最小可运行模型。
5. 你必须优先 smoke train 和 shape correctness。
6. 你不能下载外部数据。
7. 你不能调用数值求解器。
8. Task 1 可以先不依赖 checkpoint，Task 2 必须从头训练。
9. 如果训练失败，你需要读日志、定位错误、修改代码、重试。
10. 如果 smoke train 成功，你需要生成 rehearsal prediction 并调用 validator。
11. 最后输出 REHEARSAL_COMPLETE 并写 rehearsal report。
12. 如果当前没有可用的正式数据文件，不要伪造 HDF5 数据，不要尝试 smoke training，用最小代码骨架 + 明确的数据缺失报告完成 rehearsal。
13. 不要读取 submission/task1_logs.log 或 submission/task2_logs.log 这类旧会话日志，它们不属于 rehearsal 所需信息。
14. 每个响应最多只能调用一个 function tool；如果需要多个操作，必须分多轮串行调用。
"""

TEST_TOOL_LOOP_PROMPT = """请调用 write_file，在 submission/code/hello.py 写入一个最小 Python 文件。
收到工具结果后，简短总结是否成功。"""


def build_task_instruction_block(task: str) -> str:
    task = task.strip().lower()
    if task == "task1":
        return """Task 1 rules:
- Fixed-viscosity 1D Burgers.
- Input is the first 10 time steps.
- Output shape must be `(N, 200, 256)`.
- The first 10 output steps must match the test input within tolerance `1e-3`.
- official Task 1 PDEBench checkpoints may be used.
- Checkpoint directory is `workspace/checkpoints/task1_official/`.
- Write all Task 1 generated source code under `workspace/submission/code/task1/`.
- Do not keep Task 1-specific model or training logic only in the `workspace/submission/code/` root.
- Output file is `workspace/submission/task1_pred.hdf5`.
- Logs and time file are `task1_logs.log` and `task1_time.csv`.
- Training time affects score, so prefer efficient experiments."""
    if task == "task2":
        return """Task 2 rules:
- Multi-viscosity 1D Burgers.
- Input is the first 10 time steps.
- Output shape must be `(N, 200, 256)`.
- The first 10 output steps must match the test input within tolerance `1e-3`.
- The model must be trained from scratch.
- Do not use Task 1 data, Task 1 checkpoint, or Task 1 fine-tuned weights.
- Do not use external pretrained weights.
- Viscosity may be used during training if available, but test-time viscosity is unavailable.
- Write all Task 2 generated source code under `workspace/submission/code/task2/`.
- Do not keep Task 2-specific model or training logic only in the `workspace/submission/code/` root.
- Output file is `workspace/submission/task2_pred.hdf5`."""
    if task == "task3":
        return """Task 3 rules:
- Kuramoto-Sivashinsky multi-parameter prediction.
- Input is the first 20 time steps.
- Output shape must be `(1000, 400, 256)`.
- The first 20 output steps must match the test input within tolerance `1e-3`.
- train from scratch using only official KS training data.
- Test-time `lambda2` is unknown `lambda2` at test time.
- Do not use Task 1 or Task 2 weights for Task 3.
- Write all Task 3 generated source code under `workspace/submission/code/task3/`.
- Do not keep Task 3-specific model or training logic only in the `workspace/submission/code/` root.
- Output file is `workspace/submission/task3_pred.hdf5`.
- Logs must include explicit reasoning about KS dynamics, unknown-parameter strategy, model selection, and parameter inference in logs."""
    raise ValueError(f"Unsupported task {task!r}")


def build_autonomous_user_prompt(*, tasks: list[str], docs_context: str, baseline_listing: str, workspace_listing: str) -> str:
    task_text = ", ".join(tasks)
    task_blocks = "\n\n".join(build_task_instruction_block(task) for task in tasks)
    return f"""Current runner mode: autonomous
Formal session tasks: {task_text}

Formal session policy:
- Formal autonomous runs should use independent task sessions whenever possible.
- If only one task is assigned, produce only that task's artifacts and task-specific generated code.
- If multiple tasks are explicitly assigned, the same full session log must be exported to each assigned task log file.
- Do not reuse Task 1 outputs, checkpoints, generated code, or weights for Task 2 or Task 3 unless the competition rules explicitly allow it.
- Keep inference under 120 seconds per task and wall-clock under 12 hours per formal task session.

Task-specific instructions:
{task_blocks}

Competition brief and docs summary:
{docs_context}

Curated baseline listing:
{baseline_listing}

Workspace summary:
{workspace_listing}

Use a single observe -> plan -> implement -> validate -> experiment -> reflect -> finalize loop.
Decide the next step yourself, but use tools for file inspection, code generation, training, validation, debugging, and packaging.
When the current formal session is complete and all validations pass, output RUNNER_FINALIZED."""


def build_autonomous_dry_run_prompt(*, tasks: list[str], docs_context: str, baseline_listing: str, workspace_listing: str) -> str:
    task_text = ", ".join(tasks)
    task_blocks = "\n\n".join(build_task_instruction_block(task) for task in tasks)
    return f"""Current runner mode: autonomous_dry_run
Requested tasks: {task_text}

This is a dry run. Do not train, do not write `submission/code/`, do not generate predictions, and do not download data.

Allowed actions:
1. Read docs under `docs/`.
2. List data, checkpoints, baselines, and workspace files.
3. Inspect existing HDF5 files.
4. Write only `runs/autonomous_dry_run/plan.md`.
5. Summarize the next concrete plan for a formal autonomous run.

Forbidden actions:
1. Do not start training or inference shell commands.
2. Do not write `submission/code/`.
3. Do not write prediction files or time CSVs.
4. Do not download external data.
5. Do not call any numerical PDE solver.
6. Do not modify `docs/`, `agent_runner/`, or `tests/`.

Task-specific instructions:
{task_blocks}

Competition brief and docs summary:
{docs_context}

Curated baseline listing:
{baseline_listing}

Workspace summary:
{workspace_listing}

When the dry run is complete, output DRY_RUN_COMPLETE."""


def build_autonomous_rehearsal_prompt(
    *,
    tasks: list[str],
    docs_context: str,
    baseline_listing: str,
    workspace_listing: str,
    max_train_seconds_per_task: int,
) -> str:
    task_text = ", ".join(tasks)
    task_blocks = "\n\n".join(build_task_instruction_block(task) for task in tasks)
    return f"""Current runner mode: autonomous_rehearsal
Requested tasks: {task_text}
Smoke-training budget per task: {max_train_seconds_per_task} seconds

This is a rehearsal, not a formal long training run.
If no usable HDF5 files are available under `workspace/data/`, switch to the minimal code skeleton plus explicit data-missing report path. Do not fabricate training data.

Allowed actions:
1. Read docs under `docs/`.
2. List data, checkpoints, baselines, and workspace files.
3. Inspect existing HDF5 files.
4. Write training, inference, and validation code under `submission/code/`.
5. Use `run_shell` only for smoke training or smoke inference.
6. Use `validate_submission` for rehearsal or formal-format checks.
7. Analyze logs, fix failures, and retry.
8. Use snapshot and rollback before risky rewrites.
9. Write temporary rehearsal outputs under `runs/rehearsal/`.

Forbidden actions:
1. Do not run long training jobs.
2. Do not download external data.
3. Do not call any numerical PDE solver.
4. Do not modify `docs/`, `agent_runner/`, or `tests/`.
5. Do not bypass the Task 2 from-scratch restriction.

Task-specific instructions:
{task_blocks}

Competition brief and docs summary:
{docs_context}

Curated baseline listing:
{baseline_listing}

Workspace summary:
{workspace_listing}

When the rehearsal is complete, output REHEARSAL_COMPLETE."""
