from __future__ import annotations

import hashlib
import json

import h5py
import numpy as np

from agent_runner.config import RunnerConfig
from agent_runner.logger import ToolCallLogger
from agent_runner.safety import WorkspaceSafety
from agent_runner.tool_registry import build_tool_registry
from agent_runner.tools.log_tools import analyze_log
from agent_runner.tools.validate_tools import validate_submission


def test_rehearsal_profile_rejects_unbounded_train_command(workspace):
    config = RunnerConfig.from_workspace(workspace)
    registry = build_tool_registry(
        config,
        ToolCallLogger(workspace / "internal_logs" / "tool_calls.jsonl"),
    )

    result = registry.execute(
        "run_shell",
        {
            "command": "python runs/train.py --task task1",
            "profile": "rehearsal",
        },
    )

    assert result["ok"] is False
    assert "smoke" in result["error"].lower()


def test_rehearsal_profile_accepts_smoke_train_command(workspace):
    config = RunnerConfig.from_workspace(workspace)
    registry = build_tool_registry(
        config,
        ToolCallLogger(workspace / "internal_logs" / "tool_calls.jsonl"),
    )
    train_script = workspace / "runs" / "train.py"
    train_script.write_text("print('loss=0.1 smoke success')\n", encoding="utf-8")

    result = registry.execute(
        "run_shell",
        {
            "command": "python3 runs/train.py --smoke --max-batches 1",
            "profile": "rehearsal",
            "timeout_seconds": 30,
        },
    )

    assert result["ok"] is True
    assert result["data"]["returncode"] == 0


def test_write_file_updates_code_manifest_for_submission_code(workspace):
    config = RunnerConfig.from_workspace(workspace)
    registry = build_tool_registry(
        config,
        ToolCallLogger(workspace / "internal_logs" / "tool_calls.jsonl"),
    )
    registry.set_context(task_id="task1", step_id="step-001")

    content = "print('generated by llm')\n"
    result = registry.execute(
        "write_file",
        {
            "path": "submission/code/foo.py",
            "content": content,
        },
    )

    assert result["ok"] is True
    manifest_path = workspace / "submission" / "code_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert len(manifest) == 1
    assert manifest[0]["path"] == "submission/code/foo.py"
    assert manifest[0]["step_id"] == "step-001"
    assert manifest[0]["task_id"] == "task1"
    assert manifest[0]["size"] == len(content.encode("utf-8"))
    assert manifest[0]["sha256"] == hashlib.sha256(content.encode("utf-8")).hexdigest()
    assert "timestamp" in manifest[0]


def test_analyze_log_detects_failure_modes_and_smoke_success(workspace):
    safety = WorkspaceSafety(workspace)
    log_path = workspace / "runs" / "train.log"

    log_path.write_text("loss: 0.42\nval_loss: 0.30\nsmoke success\n", encoding="utf-8")
    result = analyze_log(path="runs/train.log", safety=safety)
    assert result["ok"] is True
    assert result["data"]["recommendation"] == "finalize_rehearsal"
    assert result["data"]["smoke_success"] is True

    log_path.write_text("RuntimeError: CUDA out of memory\n", encoding="utf-8")
    result = analyze_log(path="runs/train.log", safety=safety)
    assert result["data"]["recommendation"] == "reduce_model"
    assert result["data"]["oom_detected"] is True

    log_path.write_text("shape mismatch: got [8, 199, 256]\n", encoding="utf-8")
    result = analyze_log(path="runs/train.log", safety=safety)
    assert result["data"]["recommendation"] == "fix_code"
    assert result["data"]["shape_mismatch_detected"] is True

    log_path.write_text("loss=nan\n", encoding="utf-8")
    result = analyze_log(path="runs/train.log", safety=safety)
    assert result["data"]["recommendation"] == "rollback"
    assert result["data"]["nan_detected"] is True


def test_validate_submission_allows_rehearsal_subset_predictions(workspace, fake_test_hdf5):
    rehearsal_dir = workspace / "runs" / "rehearsal"
    rehearsal_dir.mkdir(parents=True, exist_ok=True)
    (workspace / "submission" / "code" / "generated.py").write_text("print('ok')\n", encoding="utf-8")

    with h5py.File(fake_test_hdf5, "r") as source:
        test_tensor = source["tensor"][:1]

    pred = test_tensor.copy()
    pred[:, 10:, :] = pred[:, 10:, :] + 0.05
    with h5py.File(rehearsal_dir / "pred.hdf5", "w") as handle:
        handle.create_dataset("pred", data=pred)
    (rehearsal_dir / "time.csv").write_text("train_time,inference_time\n1.0,0.1\n", encoding="utf-8")
    (rehearsal_dir / "logs.log").write_text(
        json.dumps(
            {
                "timestamp": "2026-05-17T00:00:00+00:00",
                "elapsed_seconds": 0.1,
                "response": "ok",
            }
        )
        + "\n",
        encoding="utf-8",
    )

    rehearsal_result = validate_submission(
        submission_dir=rehearsal_dir,
        test_hdf5=fake_test_hdf5,
        code_dir=workspace / "submission" / "code",
        rehearsal_mode=True,
    )
    assert rehearsal_result["ok"] is True
    assert rehearsal_result["data"]["rehearsal_only"] is True

    formal_result = validate_submission(
        submission_dir=rehearsal_dir,
        test_hdf5=fake_test_hdf5,
        code_dir=workspace / "submission" / "code",
        rehearsal_mode=False,
    )
    assert formal_result["ok"] is False
    assert "incompatible" in formal_result["error"].lower()
